/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UoKvkpwX24A
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"

export function Gallery() {
  return (
    (<div className="w-full max-w-6xl mx-auto px-4 py-12 md:px-6 md:py-16 lg:py-20">
      <div className="grid gap-6 md:gap-8 lg:gap-10">
        <div>
          <h2 className="text-2xl font-bold mb-4 md:text-3xl">Image Gallery</h2>
          <div
            className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6 lg:gap-8">
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Image 1"
              className="w-full h-64 object-cover rounded-lg"
              style={{ aspectRatio: "600/400", objectFit: "cover" }} />
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Image 2"
              className="w-full h-64 object-cover rounded-lg"
              style={{ aspectRatio: "600/400", objectFit: "cover" }} />
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Image 3"
              className="w-full h-64 object-cover rounded-lg"
              style={{ aspectRatio: "600/400", objectFit: "cover" }} />
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Image 4"
              className="w-full h-64 object-cover rounded-lg"
              style={{ aspectRatio: "600/400", objectFit: "cover" }} />
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Image 5"
              className="w-full h-64 object-cover rounded-lg"
              style={{ aspectRatio: "600/400", objectFit: "cover" }} />
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Image 6"
              className="w-full h-64 object-cover rounded-lg"
              style={{ aspectRatio: "600/400", objectFit: "cover" }} />
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4 md:text-3xl">Video Documentaries</h2>
          <div
            className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6 lg:gap-8">
            <Card className="overflow-hidden rounded-lg shadow-lg">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Video 1"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              <CardContent className="p-4">
                <h3 className="text-lg font-semibold mb-2">Exploring the Wonders of Nature</h3>
                <p className="text-muted-foreground">
                  A captivating documentary that takes you on a journey through the breathtaking landscapes and diverse
                  ecosystems of our planet.
                </p>
              </CardContent>
            </Card>
            <Card className="overflow-hidden rounded-lg shadow-lg">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Video 2"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              <CardContent className="p-4">
                <h3 className="text-lg font-semibold mb-2">The Rise of Sustainable Living</h3>
                <p className="text-muted-foreground">
                  Discover how individuals and communities are embracing eco-friendly practices to create a more
                  sustainable future.
                </p>
              </CardContent>
            </Card>
            <Card className="overflow-hidden rounded-lg shadow-lg">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Video 3"
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              <CardContent className="p-4">
                <h3 className="text-lg font-semibold mb-2">The Art of Mindful Living</h3>
                <p className="text-muted-foreground">
                  Explore the transformative power of mindfulness and how it can enrich our lives and foster inner
                  peace.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>)
  );
}
